apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluentd.conf: |
    # Fluentd configuration goes here
    # Example: Input from Kubernetes logs and output to Elasticsearch
    <source>
      @type tail
      format json
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-pos.log
      tag kubernetes.*
    </source>

    <match kubernetes.**>
      @type elasticsearch
      host elasticsearch-logging
      port 9200
      logstash_format true
      flush_interval 5s
    </match>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.14.3-debian-1
          env:
            - name: FLUENTD_CONF
              value: "fluentd.conf"
          volumeMounts:
            - mountPath: /fluentd/etc/fluentd.conf
              name: fluentd-config
              subPath: fluentd.conf
            - mountPath: /var/log/containers
              name: varlog
              readOnly: true
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config
        - name: varlog
          hostPath:
            path: /var/log/containers
