apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: nginx
  labels:
    app: front
spec:
  containers:
    - name: nginx
      image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nginx:1.27.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80