apiVersion: batch/v1
kind: Job
metadata:
  name: nginx
  namespace: default
spec:
  ttlSecondsAfterFinished: 50
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: nginx
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nginx:1.27.0
          command:
            - /bin/bash
          args:
            - -c
            - echo 124