apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: default
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: os
                    operator: In
                    values:
                      - linux
                      - windows
      containers:
        - name: nginx
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nginx:1.27.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080


