apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: cmdb-sync-asset-code
  managedFields:
    - apiVersion: batch/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:concurrencyPolicy: {}
          f:failedJobsHistoryLimit: {}
          f:jobTemplate:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:activeDeadlineSeconds: {}
              f:backoffLimit: {}
              f:completions: {}
              f:parallelism: {}
              f:template:
                f:metadata:
                  f:labels:
                    .: {}
                    f:app: {}
                f:spec:
                  f:containers:
                    k:{"name":"sync-asset-code"}:
                      .: {}
                      f:command: {}
                      f:image: {}
                      f:imagePullPolicy: {}
                      f:name: {}
                      f:resources:
                        .: {}
                        f:limits:
                          .: {}
                          f:cpu: {}
                          f:memory: {}
                      f:terminationMessagePath: {}
                      f:terminationMessagePolicy: {}
                  f:dnsPolicy: {}
                  f:restartPolicy: {}
                  f:schedulerName: {}
                  f:securityContext: {}
                  f:terminationGracePeriodSeconds: {}
          f:schedule: {}
          f:successfulJobsHistoryLimit: {}
          f:suspend: {}
      manager: dashboard
      operation: Update
      time: "2021-12-08T10:36:07Z"
    - apiVersion: batch/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:lastScheduleTime: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-12-31T04:34:00Z"
  name: cmdb-sync-asset-code
  namespace: cmdb
  selfLink: /apis/batch/v1beta1/namespaces/cmdb/cronjobs/cmdb-sync-asset-code
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app: cmdb-sync-asset-code
    spec:
      activeDeadlineSeconds: 7200
      backoffLimit: 0
      completions: 1
      parallelism: 1
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: cmdb-sync-asset-code
        spec:
          containers:
            - command:
                - /root/sync_data
                - -server_asset_code
                - -switch_asset_code
              image: harbor.intra.ke.com/dayu/kubeservice/devops/cmdb/sync_tx_could:master.1.0.25
              imagePullPolicy: Always
              name: sync-asset-code
              resources:
                limits:
                  cpu: "2"
                  memory: 2Gi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 34 12 * * 2
  successfulJobsHistoryLimit: 10
  suspend: false
status:
  lastScheduleTime: "2024-12-31T04:34:00Z"