apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: cmdb-sync-tx-clouds
  managedFields:
    - apiVersion: batch/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:concurrencyPolicy: {}
          f:failedJobsHistoryLimit: {}
          f:jobTemplate:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:activeDeadlineSeconds: {}
              f:backoffLimit: {}
              f:completions: {}
              f:parallelism: {}
              f:template:
                f:spec:
                  f:containers:
                    k:{"name":"sync-tx-cloud"}:
                      .: {}
                      f:command: {}
                      f:image: {}
                      f:imagePullPolicy: {}
                      f:name: {}
                      f:resources:
                        .: {}
                        f:limits:
                          .: {}
                          f:cpu: {}
                          f:memory: {}
                        f:requests:
                          .: {}
                          f:cpu: {}
                          f:memory: {}
                      f:terminationMessagePath: {}
                      f:terminationMessagePolicy: {}
                  f:dnsPolicy: {}
                  f:restartPolicy: {}
                  f:schedulerName: {}
                  f:securityContext: {}
                  f:terminationGracePeriodSeconds: {}
          f:schedule: {}
          f:successfulJobsHistoryLimit: {}
          f:suspend: {}
      manager: dashboard
      operation: Update
      time: "2022-04-25T08:33:44Z"
    - apiVersion: batch/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:active: {}
          f:lastScheduleTime: {}
      manager: kube-controller-manager
      operation: Update
      time: "2025-01-03T02:35:06Z"
  name: cmdb-sync-tx-clouds
  namespace: cmdb
  selfLink: /apis/batch/v1beta1/namespaces/cmdb/cronjobs/cmdb-sync-tx-clouds
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app: cmdb-sync-tx-clouds
    spec:
      activeDeadlineSeconds: 1200
      backoffLimit: 2
      completions: 1
      parallelism: 1
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - command:
                - /root/sync_data
                - -tx_cloud
              image: harbor.intra.ke.com/dayu/kubeservice/devops/cmdb/sync_tx_could:master.1.0.28
              imagePullPolicy: Always
              name: sync-tx-cloud
              resources:
                limits:
                  cpu: "1"
                  memory: 1Gi
                requests:
                  cpu: 900m
                  memory: 1Gi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 30
  suspend: false
status:
  active:
    - apiVersion: batch/v1
      kind: Job
      name: cmdb-sync-tx-clouds-1735871700
      namespace: cmdb
      resourceVersion: "80934949512"
      uid: c4648d82-1ab9-4218-b2d5-43336b3794c4
  lastScheduleTime: "2025-01-03T02:35:00Z"