apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: default
  name: nginx
spec:
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: nginx
              image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nginx:1.27.0
  schedule: "*/1 * * * *"
