apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cmdb-eventserver
  name: cmdb-eventserver
  namespace: cmdb
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cmdb-eventserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cmdb-eventserver
    spec:
      containers:
        - env:
            - name: ZK
              value: zk01.matrix.mars.lianjia.com:2181,zk02.matrix.mars.lianjia.com:2181,zk03.matrix.mars.lianjia.com:2181
            - name: LOGV
              value: "5"
          image: registry.ke.com/docker-virtual/common/cmdb/cmdb_eventserver:master.83
          imagePullPolicy: Always
          name: cmdb-eventserver
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: "2"
              memory: 1Gi