apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rolling-update
  template:
    metadata:
      labels:
        app: rolling-update
    spec:
      containers:
        - name: rolling-update
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/quay.io/opstree/redis:v7.0.5
          ports:
            - containerPort: 63791

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1