apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: douzengrui
rules:
  - apiGroups:
      - ''
    verbs:
      - get
      - list
      - watch
    resources:
      - pods