apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  restartPolicy: Always
  containers:

    - name: nginx
      command:
        - /bin/sh
      args:
        - -c
        - echo hello world && nginx
        - nginx
      image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nginx:1.27.0
      imagePullPolicy: IfNotPresent