apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/redis:7.0.14
      ports:
        - containerPort: 6379
      volumeMounts:
        - mountPath: /data
          name: mount-path
  volumes:
    - name: mount-path
      hostPath:
        path: /home/docker
        type: Directory
