apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: nginx
spec:
  containers:
    - name: nginx
      imagePullPolicy: IfNotPresent
      image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nginx:1.27.0
      livenessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1