apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: nginx
spec:
#  securityContext:
#    fsGroup: 1000
  containers:
    - name: nginx
      image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nginx:1.27.0
#      securityContext:
#        runAsNonRoot: true
#        runAsUser: 1000
#        runAsGroup: 1000
      ports:
        - containerPort: 80
