apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: busybox

spec:
  containers:
    - name: busubox
      image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - sleep
        - infinity
  dnsConfig:
    nameservers:
      - 8.8.8.8
  dnsPolicy: Default