apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oom
  template:
    metadata:
      labels:
        app: oom
    spec:
      containers:
        - name: oom
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/dockeruserdou/oom-py:latest
          volumeMounts:
            - mountPath: /data
              name: oom
      volumes:
        - name: oom
          emptyDir:
            medium: ""
            sizeLimit: 1Gi
