apiVersion: v1
kind: Pod
metadata:
  name: oom
spec:
  containers:
    - name: oom
      image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/dockeruserdou/oom-py:latest
      volumeMounts:
        - mountPath: /data
          name: oom
  volumes:
    - name: oom
      emptyDir:
        medium: ""
        sizeLimit: 1Gi
